version: '3.7'

services:
  caramel:
    # If experiencing errors like "operation not permitted" when running the container as non root user
    # Try using ghcr.io/kittensaredabest/caramel:latest-debian instead of ghcr.io/kittensaredabest/caramel:latest
    image: ghcr.io/kittensaredabest/caramel:latest
    
    # Container Behavior
    restart: always
    hostname: looking-glass
    
    # User and Networking
    user: "0:0"  # Remove if not using BIRD
    network_mode: host  # Required for IPv6 support due to Docker networking limitations
    
    # Volume Configuration
    volumes:
      - /run/bird/bird.ctl:/var/run/bird.ctl  # Remove if not using BIRD, make sure that you're removing the whole volumes section, as it can't be empty
    
    # Environment Variables
    environment:
      CORS_ORIGIN: "https://lg.example.com"  # Replace with your domain (required)
      BGP_ENABLED: "true"  # Enable or disable BGP queries
      PINGTRACE_ENABLED: "false"  # Enable or disable ping, traceroute, and MTR
